---
- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
- name: Start nginx
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true
- name: Create config for Nginx
  become: true
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: reload-nginx
- name: Lighthouse | install dependencies
  become: true
  ansible.builtin.apt:
    name: git
    state: present
- name: Lighthouse | Copy from git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_repo }}"
    dest: "{{ lighthouse_dir }}"
    version: master
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: "templates/lighthouse.conf.j2"
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: "0644"
  notify: reload-nginx
