---
  - src: https://github.com/AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.11.0"
    name: ansible-clickhouse

  - src: https://github.com/Midzaru2011/vector-role.git
    scm: git
    version: "1.0.2"
    name: vector-role

