---
all:
  hosts:
    sonar-01:
      ansible_host: 62.84.124.130
    nexus-01:
      ansible_host: 84.201.173.85
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: <someuser>